// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeECysrgAM7BIHBadYN-2soeqAT3Z1Tz4',
    appId: '1:247917390246:web:16fdc8c2352fb2ca380767',
    messagingSenderId: '247917390246',
    projectId: 'coffee-spark-ai-barista-844b4',
    authDomain: 'coffee-spark-ai-barista-844b4.firebaseapp.com',
    storageBucket: 'coffee-spark-ai-barista-844b4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATd_L83kwDd57xNdrWBrBjcnXA6ye7muM',
    appId: '1:247917390246:android:9b95fae562048013380767',
    messagingSenderId: '247917390246',
    projectId: 'coffee-spark-ai-barista-844b4',
    storageBucket: 'coffee-spark-ai-barista-844b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChRKUnLCqzntlqsFzH2Hh5_DYoh7UrZWk',
    appId: '1:247917390246:ios:c9683688222cc6be380767',
    messagingSenderId: '247917390246',
    projectId: 'coffee-spark-ai-barista-844b4',
    storageBucket: 'coffee-spark-ai-barista-844b4.firebasestorage.app',
    iosBundleId: 'com.example.zaikiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChRKUnLCqzntlqsFzH2Hh5_DYoh7UrZWk',
    appId: '1:247917390246:ios:c9683688222cc6be380767',
    messagingSenderId: '247917390246',
    projectId: 'coffee-spark-ai-barista-844b4',
    storageBucket: 'coffee-spark-ai-barista-844b4.firebasestorage.app',
    iosBundleId: 'com.example.zaikiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeECysrgAM7BIHBadYN-2soeqAT3Z1Tz4',
    appId: '1:247917390246:web:cb36a5ed4d67e746380767',
    messagingSenderId: '247917390246',
    projectId: 'coffee-spark-ai-barista-844b4',
    authDomain: 'coffee-spark-ai-barista-844b4.firebaseapp.com',
    storageBucket: 'coffee-spark-ai-barista-844b4.firebasestorage.app',
  );

}